### ISSUE TITLE
Unable to import

### ISSUE THREAD

**Issue by slawek-mazur** [awslabs/aws-mobile-react-sample#10]
When I click the button import ends up with 

> Malformed project configuration files. Resource creation failed for reactsample-deployments-mobilehub-974252575 bucket.

When I download as a zip a try to import file (zip is too large at first, one of graphics have to be removed) message I got is 

> Malformed project configuration files. No project found in configuration files. Expected filename : mobile-hub-project.yml

**Comment by yujinlyj** [comment]
Hi,

Do you mean the zip file "aws-mobile-react-sample-master.zip"?

If yes, after you unzip it, you'll find in folder "aws-mobile-react-sample-master\backend\import_mobilehub/" there is another zip file called "react-sample.zip".

You will need to use this react-sample.zip instead for the import in mobile hub.

Hope this helps :)

**Comment by slawek-mazur** [comment]
that was my bad. everything looks good.
