### ISSUE TITLE
Restaurant Ordering step-by-step tutorial fails

### ISSUE THREAD

**Issue by roosi** [awslabs/aws-mobile-react-sample#12]
Following the step-by-step tutorial on Mobile hub fails. Steps to produce:

1. Create Mobile Hub project using Restaurant Ordering starter kit and follow instructions
2. Clone this project
3. awsmobile init <project id>

```
>awsmobile run

building backend
   generating backend project content
   backend project content generation successful

Successfully built backend, build artifacts are saved at:
C:\xxx\aws-mobile-react-sample\awsmobilejs\.awsmobile\backend-build

preparing for backend project update: Restaurant Ordering
done

updating backend project: Restaurant Ordering
Failed to update project Restaurant Ordering
{ BadRequestException: Unable to find build artifact uploads/lambda-archive.zip in S3 bucket restaurantordering-deployments-mobilehub-xxx for API function ReactSample
    at Object.extractError (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\protocol\json.js:48:27)
    at Request.extractError (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\protocol\rest_json.js:52:8)
    at Request.callListeners (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\request.js:683:14)
    at Request.transition (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\xxx\AppData\Roaming\npm\node_modules\awsmobile-cli\node_modules\aws-sdk\lib\request.js:685:12)
  message: 'Unable to find build artifact uploads/lambda-archive.zip in S3 bucket restaurantordering-deployments-mobilehub-xxx for API function ReactSample',
  code: 'BadRequestException',
  time: 2017-12-08T11:01:38.740Z,
  requestId: 'xxx',
  statusCode: 400,
  retryable: false,
  retryDelay: 70.77565621418229 }
```

**Comment by Sniedes722** [comment]
@roosi also experiencing this issue when trying to deploy with Ubuntu 16.04

**Comment by angeliski** [comment]
Me too. Using a macOs sierra 10.12

**Comment by dwatts418** [comment]
Me three!  Windows 10

**Comment by angeliski** [comment]
Any progress @mlabieniec ? Could be any missing permission? Could I help you with something?

**Comment by mlabieniec** [comment]
The starter has not yet been updated to support the cli project structure yet. We are currently updating all the starters to properly use cli/amplify. For this current project you would need to use the instructions currently in the readme. This is in our current backlog, and we will try to get this updated asap.

**Comment by angeliski** [comment]
Thank you @mlabieniec, I will try use the readme to run the project

**Comment by elorzafe** [comment]
You can do the following, after one click import. You will see the instructions on how integrate your project.

The steps will be like this a
on your browser
Go to AWS MobileHub
On StarterKits click on restaurant ordering
Set the name for your project, click next
On Setup your starter kit Click next button (Wait until is ready, takes a couple of minutes the backend to be ready)
On Setup your backend copy the line that says awsmobile init asdad-123123-1231-a-adasd-sas (that line has the project id)

on your terminal
git clone https://github.com/awslabs/aws-mobile-react-sample.git
cd aws-mobile-react-sample
awsmobile init asdad-123123-1231-a-adasd-sas (replace it with the values you copy before)
When is asking for your src folder answer: client/src
You can set default options for the other --> Done
npm start

**Comment by angeliski** [comment]
@elorzafe  Does'nt work
![error_aws](https://user-images.githubusercontent.com/1574240/34455956-969a893e-ed71-11e7-97f8-757229e96cba.gif)

**Comment by alessandrobologna** [comment]
I managed to get it running by executing `npm install -g webpack webpack-dev-server` after the `awsmobie init ...` step, then `cd client`, `cp ./src/aws-exports.js ./src/configuration/`, `npm install` and finally `npm-start`
