### ISSUE TITLE
Move src to top-level

### ISSUE THREAD

**Issue by haraldrudell** [awslabs/aws-mobile-react-sample#13]
Because this is a **React** project, it would be an improvement to move the **client/src** with **package.json** directory to the top level and have backend and what not being random directories at that level. There could be cases where a top-level ```node_modules``` directory is trouble.

**webpack.config.js** could be in **config/webpack.config.js**
**babel-preset-env** should be used, more like
```js
        exclude: /node_modules/,
        use: {
          loader: require.resolve('babel-loader'),
          options: {
            presets: ['react', 'env', 'stage-2'],
          },
       },
```
The directive ```resolve. modules: [path.resolve('src'), 'node_modules'],``` could be used for imports.

.jsx and semicolons is out of date

I am not sure if multi-tier would affect this (iOS / Android / react-native)
It would be cool if all could share project directory, but this may not be practical or useful

**Comment by nidsharm** [comment]
Hi @haraldrudell,

Your suggestion about project structuring according to React project is correct. However, this sample was aimed at explaining the code structuring for AWS services with a distinction between client-side code (your app code) and backend (the lambda function to be uploaded to API Gateway). The aim is to help developers understand AWS Services integration with their web apps. 
Regards,
Nidhi
