### ISSUE TITLE
Disable MFA

### ISSUE THREAD

**Issue by kamipatel** [awslabs/aws-mobile-react-sample#17]
I am not able to disable MFA in this Cognito Pool. Any suggestions? Thanks!

**Comment by mlabieniec** [comment]
@kamipatel you can disable MFA via the Amazon Cognito User Pools Console:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-mfa.html

**Comment by kamipatel** [comment]
It says MFA can not be turned off if SMS role is configured. Where do I remove it from? Thanks!

**Comment by kamipatel** [comment]
Disabling MFA is grayed out. Also hot reload causes MFA and it is just annoying. Any suggestions to disable? Thanks!

**Comment by blincoln** [comment]
@kamipatel - did you resolve this?  If so, mind sharing?
