### ISSUE TITLE
Support for ITU E.164 Phone Numbers

### ISSUE THREAD

**Issue by apackeer** [awslabs/aws-mobile-react-sample#2]
Hi,

Do you accept pull requests?

The client registration page only accepts US Phone numbers. I believe you should support the full ITU E.164 range of numbers that SNS supports through Cognito User Pools. 

Register.jsx should be:
```
    checkPhonePattern = (phone) => {
        // return /\+1[0-9]{3}[0-9]{3}[0-9]{4}$/.test(phone);
        return /\+?[1-9]\d{5,15}$/.test(phone);
    }
```

**Comment by nidsharm** [comment]
Hey Arden, 

We do accept pull requests, if you can make the necessary changes to Register.jsx, we can merge your code in. 

Thanks, 
Nidhi
