### ISSUE TITLE
New to React, is this standard to logout on beforeunload?

### ISSUE THREAD

**Issue by wsheldon** [awslabs/aws-mobile-react-sample#25]
Possible newbie question but why logout on beforeunload?  Seems like it should only be explicit on 'Logout' link.

https://github.com/awslabs/aws-mobile-react-sample/blob/7bc5cf1774eb7a54567c734378500d1678d4a97d/client/src/index.js#L50

Thanks,
WS

**Comment by elorzafe** [comment]
Hi @wsheldon 

Is ok, feel free to ask if you have any question. 

window.addEventListener('beforeunload', this.handleWindowClose); means that when a user close the tab on the browser that will trigger beforeunload event and that will handle signout.

Thanks
Francisco
