### ISSUE TITLE
Error when trying to execute npm install

### ISSUE THREAD

**Issue by terencemackie** [awslabs/aws-mobile-react-sample#3]
I tried installing the sample app. All went well until the step "npm install". The error was:
Failed at the pngquant-bin@3.1.1 postinstall script 'node lib/install.js'.

This is on Ubuntu 16.04 LTS with node v4.2.6 and npm v3.5.2.

Attached is the log file from my 4th attempt.
[npm-debug.log.zip](https://github.com/awslabs/aws-mobile-react-sample/files/1204434/npm-debug.log.zip)

**Comment by nidsharm** [comment]
Hi Terence,

The log file you have provided us with mentions that two of the dependencies: fsevents and pngquant-bin fail to install. 
Could you update your npm and node versions,  remove the node_modules folder from your package and try running npm install again. 

Please let us know if you still run into this issue after the update too. 

Thanks,
Nidhi
