### ISSUE TITLE
Import project configuration fails

### ISSUE THREAD

**Issue by hutch120** [awslabs/aws-mobile-react-sample#4]
Hi Guys,

I just attended the Devday in Melbourne, Australia, and was directed here to check this out. But I'm not getting far. Fails on step 1 !! See attached image. Not even sure how to get more details on the error.

![image](https://user-images.githubusercontent.com/1034955/30197999-a7f01828-94ae-11e7-9cc9-dcac728d0a9e.png)

Any tips?

**Comment by nidsharm** [comment]
Hi hutch120,

We suspect this might be due to latency issues and are looking into it now. Is this an intermittent issue or do you face it every time you try to import a project?

Regards,
Nidhi

**Comment by hutch120** [comment]
@nidsharm Thanks for looking into this.

I've tried to build this mobile hub project a few times using this script, and it has never given me a succeeded message as I would have expected. But it has given some different error messages.

One time it appeared to have build a system, and the web page was accessible, but still had an error message that time (it was a bit different than the one above).

Just tried it now, and got the error in the attached screenshot after about 30-60 seconds. (Before I could even enter a project name)

![image](https://user-images.githubusercontent.com/1034955/30354579-b690402c-9870-11e7-815e-a2e96a321709.png)

**Comment by hutch120** [comment]
@nidsharm I tried a few more times just now and I keep getting the following error `Project already exists with that name. Please choose a new  project name.`

So I picked a really unusual name (see screenshot), and I still get the error! Is there any way to dig down into these error messages?

![image](https://user-images.githubusercontent.com/1034955/30355133-adf27328-9874-11e7-92d6-3da0358e2bf8.png)

**Comment by hutch120** [comment]
Ok, so I just refreshed Mobile Hub and it appears all the projects have actually been created, despite the error. But are they actually completely built??

![image](https://user-images.githubusercontent.com/1034955/30355243-6aec13a8-9875-11e7-9a7d-b37f68d1e80c.png)

**Comment by mitchallen** [comment]
I'm seeing this too. I'm trying to import using the link below and trying to import the same file from my local drive. I tried refresh, but no sign of the prohect

https://console.aws.amazon.com/mobilehub/home?#/?config=https://github.com/awslabs/aws-mobile-react-sample/blob/master/backend/import_mobilehub/react-sample.zip

https://github.com/awslabs/aws-mobile-react-sample/blob/master/backend/import_mobilehub/react-sample.zip

**Comment by toyeebgodo** [comment]
I have twice experienced the same issue that @hutch120 excellently described above and all I had to do was refresh Mobile Hub as he suggested. On one occasion, I had to go back and hit the "Deploy to AWS Mobile Hub" button on github again, then refresh the AWS Mobile Hub console after importing project before I found my project in the console.
